[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HallThruster = "2311f341-5e6d-4941-9e3e-3ce0ae0d9ed6"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
