[model]
num_blocks = 3
channel_mult = [1, 2, 3, 4, 5]
data_std = 0.5
label_dim = 9
resolution = 128
in_channels = 19
base_channels = 192

[training]
epochs = 10
decay_epochs = 2
lr = 2e-3
min_lr = 1e-5
eval_freq = 200
ema = 0.995
checkpoint_freq = 20
use_checkpoint = true
folder = "large"
batch_size = 128
weight_decay = 0.00
adam_betas = [0.9, 0.995]