[model]
down_layers = 1
mid_layers = 1
up_layers = 1
channel_mult = [1,2,3,4,5]
data_std = 1.0
label_dim = 9
resolution = 128
in_channels = 19

[training]
epochs = 1
anneal = false
lr = 1.5e-4
min_lr = 1e-5
eval_freq = 50
ema = 0.995
checkpoint_freq = 10
use_checkpoint=false
folder = "xs"
batch_size=2048
weight_decay = 0.01
adam_betas = [0.9, 0.95]