# Which plasma properties should be held constant during sampling. An empty list gives unconditional samples.
fields_to_keep = ["B", "ui_1"]
# Number of independent sample traces to generate
num_samples = 64
# Batch size of sample generation. If not provided, we do a single batch
batch_size = 64
# Number of sampling steps to take
num_steps = 1024

# Which model to load (ema, best, last)
model_type = "ema"
# Output directory for generations.
out_dir = "samples/noTe"
# Whether samples in out_dir should be replaced or added to
replace_samples = true
# Step scale
step_scale = 1.00

[observation]
# Folder containing (normalized) simulation info to condition on.
# If not provided, we sample unconditionally.
file = "mcmc_reference/ref_sim/normalized"

# Default stddev
std_dev = 1.5

[observation.fields]
B = { locs = "all", error_type = "relative", std_dev = 1.0 }
#ui_1 = { locs = [0.025, 0.03], error_type = "relative", std_dev = 1.0}
ui_1 = { locs = [0.015, 0.02, 0.0225, 0.025, 0.02625, 0.0275, 0.03, 0.035, 0.04, 0.045], error_type = "relative", std_dev = 1.0}
#ui_1 = { locs = "all", error_type = "relative", std_dev = 0.8 }
#ne = { locs = [0.01], error_type = "relative", std_dev = 8.0 }

