# Number of independent sample traces to generate
num_samples = 64
# Batch size of sample generation. If not provided, we do a single batch
batch_size = 256
# Number of sampling steps to take
num_steps = 1024

# Which model to load (ema, best, last) 
model_type = "ema"
# Output directory for generations.
out_dir = "samples/noTe"
# Whether samples in out_dir should be replaced or added to
replace_samples = true
# Step scale
step_scale = 1.2

observation = "experimental_data/data_pb=3.5e-5.toml"