# Number of independent sample traces to generate
num_samples = 16384
# Batch size of sample generation. If not provided, we do a single batch
batch_size = 1024
# Number of sampling steps to take
num_steps = 2048

# Which model to load (ema, best, last)
model_type = "ema"
# Output directory for generations.
out_dir = "samples/sample_21_uncond"
# Whether samples in out_dir should be replaced or added to
replace_samples = false
# Step scale
step_scale = 1.0

# Data dir for unconditional sample generation
# Only read if no observation present
unconditional_data_dir ="/home/marksta/scratch/hall_diffusion/data/test_large"


